#The name of the team (the same you used to create the namespace)
team: team-dev-ops
#The name of the API
nameOverride: hamuste
useAirbag: false
ingress:
  enabled: true
  #DNS of your API. Traffic to those DNS address will be routed to your API
  hosts:
    #Used by traffic manager
    - hamuste.mysoluto.com
    #Used to directly reference primary cluster
    - hamuste-primary.mysoluto.com
    #Used to directly reference secondary cluster
    - hamuste-secondary.mysoluto.com
#optional environment variables
config:
  #Key: Value
service:
  internalPort: 9999
  isAlivePath: /api/v1/isAlive

image:
  version: 1.0
  pullPolicy: IfNotPresent

volumeMounts:
  - name: secrets-volume
    mountPath: /home/dotnet/app/secrets
volumes:
  - name: secrets-volume
    secret:
      secretName: hamuste-secret 