version: 2
jobs:
  build_api:
    machine: true

    steps:
      - checkout
      - run:
          name: Build decryptor docker image
          command: docker build . -t soluto/kamus-decryptor
      - run:
          name: Build encryptor docker image
          command: docker build . -t soluto/kamus-encryptor --build-arg PROJECT_NAME=encrypt-api

      - run:
          name: Run black box tests
          command: docker-compose -f tests/blackbox/compose/docker-compose.yaml up --build --exit-code-from black-box --abort-on-container-exit
          environment:
            ENCRYPTOR_IMAGE: soluto/kamus-encryptor
            DECRYPTOR_IMAGE: soluto/kamus-decryptor
  run_tests:
    docker:
      - image: microsoft/dotnet:2.1-sdk

    steps:
      - checkout
      - run:
          name: Run unit tests
          working_directory: "tests/unit"
          command: dotnet test
      - run:
          name: Run integration
          working_directory: "tests/integration"
          command: dotnet test

  build:
    machine: true

    steps:
      - checkout
      - run:
          name: Build docker image
          working_directory: "init-container"
          command: docker build . -t kamus-init-container

      - run:
          name: Run black box tests
          working_directory: "init-container/tests"
          command: sudo INIT_CONTAINER_IMAGE=kamus-init-container ./run_test.sh
      - run:
          name: Save docker image
          command: |
            mkdir -p docker-cache
            docker save -o docker-cache/built-image.tar kamus-init-container
      - save_cache:
          key: docker_cache_key
          paths:
            - docker-cache
  push:
    machine: true

    steps:
      - restore_cache:
          key: docker_cache_key
      - run:
          name: Restore imahe
          command: |
            docker load < docker-cache/built-image.tar
            docker tag kamus-init-container soluto/kamus-init-container:$CIRCLE_BUILD_NUM
      - run:
          name: Docker push
          working_directory: "init-container/tests"
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD 
            docker push soluto/kamus-init-container:$CIRCLE_BUILD_NUM
      - run:
          name: Docker push latest
          working_directory: "init-container/tests"
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD 
            docker tag soluto/kamus-init-container:$CIRCLE_BUILD_NUM soluto/kamus-init-container:latest
            docker push soluto/kamus-init-container:latest
workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - push:
          requires:
            - build
          filters:
            branches:
              only: master
  api:
    jobs:
      - build_api
      - run_tests

