version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout
      - run:
          name: Build decryptor docker image
          command: docker build . -t soluto/kamus-decryptor
      - run:
          name: Build encryptor docker image
          command: docker build . -t soluto/kamus-encryptor --build-arg PROJECT_NAME=encrypt-api

      - run:
          name: Run black box tests
          command: docker-compose -f tests/blackbox/compose/docker-compose.yaml up --build --exit-code-from black-box --abort-on-container-exit
          environment:
            ENCRYPTOR_IMAGE: soluto/kamus-encryptor
            DECRYPTOR_IMAGE: soluto/kamus-decryptor
workflows:
  version: 2
  build_and_push:
    jobs:
      - build

