kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hamuste
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]